.TH DAB 6 "December 24, 2003"
.\"	$NetBSD: dab.6,v 1.1.1.1 2003/12/26 17:57:04 christos Exp $
.\"
.\" Copyright (c) 2003 Thomas Klausner.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.SH NAME
dab \- Dots and Boxes game
.SH SYNOPSIS
.B dab
[\fB\-aw\fP]
[\fB\-n\fP \fIngames\fP]
[\fB\-p\fP Ao \fIc|h\fP Ac Ns Ao \fIc|h\fP Ac]
[\fIxdim\fP Oo \fIydim\fP Oc]
.SH DESCRIPTION
.B dab
is a game where each player tries to complete the most
boxes.
A turn consists of putting one border of a box; the player
setting the fourth and final border of a box gets the
point for the box and has another turn.
.PP
The keys used are the vi keys:
\fBk\fP
for up,
\fBj\fP
for down,
\fBh\fP
for left, and
\fBl\fP
for right.
To switch between even and odd rows, use one of the following
keys:
\fBu\fP
(diagonal right up ,)
\fBy\fP
(diagonal left up ,)
\fBb\fP
(diagonal left down ,)
\fBn\fP
(diagonal right down ;)
<Ic space>
sets a new border,
\fBCTRL-L\fP
and
\fBCTRL-R\fP
redraw the screen, and
\fBq\fP
quits the game.
.PP
Support options are:
.TP
\fB\-a\fP
Don't use the alternate character set.
.TP
\fB\-n\fP \fIngames\fP
\fIngames\fP
games will be played.
(Especially useful in Fl p Ar cc No mode.)
.TP
\fB\-p\fP Ao \fIc|h\fP Ac Ns Ao \fIc|h\fP Ac
Select which of the two players is a human
or a computer.
The first argument is the first player;
\fBc\fP
stands for computer and
\fBh\fP
for human.
.TP
\fB\-w\fP
Wait for a character press between games.
.PP
.PP
\fIxdim\fP
and
\fIydim\fP
define the size of the board in the x and y
dimensions.
.SH AUTHORS
Christos Zoulas
<christos@NetBSD.org>
.SH SEE ALSO
.PP
.%A Elwyn R. Berlekamp
.%T The Dots and Boxes Game: Sophisticated Child's Play
.%D 2000
.%I A K Peters
.%O http://www.akpeters.com/book.asp?bID=111

